from common_functions import *
import pygame
import pygame.freetype 

NOTIF_TITLE = "automind"
APP_VER = "0.0.1.5"
APP_NAME = "Automind MIDI Configurator"
APP_NAME_SNAKE = "automindMidiApp"

pygame.init()
ASSETS_PATH = './assets/'
FONTS_PATH = ASSETS_PATH + 'fonts/'
icon = pygame.image.load(f'{ASSETS_PATH}{APP_NAME_SNAKE}Icon.png')
CONFIG_FILE_NAME = f"{APP_NAME_SNAKE}Config.json"
pygame.display.set_icon(icon)
pygame.font.init()
TEXT_BRIGHTNESS = 0.95
TEXT_ALPHA = 0.8
TEXT_SIZE = int(20)

configLoad(CONFIG_FILE_NAME)

TEXT_FAMILY = f'{FONTS_PATH}bedstead-condensed.otf'
# TEXT_FAMILY = f'{FONTS_PATH}bedstead-extracondensed.otf'
# TEXT_FAMILY = f'{FONTS_PATH}Unitblock.ttf'
# TEXT_FAMILY = f'{FONTS_PATH}PixeloidMono-d94EV.ttf'
PIXELS_PER_SYMBOL = TEXT_SIZE/12 * 80/12
globalText = ["oh, hi mark"]

BG_COLOR = (20,15,10)
SCREEN_W = 600
SCREEN_H = 650

RENDER_GRID = True
RENDER_FREE_CELLS = True
RENDER_FREE_CELLS_PIXELS_AT_CENTER = True
GRID_COLOR = (150,150,150,30)
GRID_SIZE_PX_X = 25
GRID_SIZE_PX_Y = GRID_SIZE_PX_X
GRID_CELL_BORDER_PX = (2,2)
BRICKS_OUTLINE_RADIUS_PX = 4

BRICKS_OUTLINE_WIDTH_PX = 3

DEFAULT_RANGE_BOUNDS = (0,100)

HOVER_COLOR_MULTS = (1.5, 1.5, 1.5)
ACTIVE_COLOR_MULTS = (-1, -1, -1)

LP_SLOW_COEF = 0.95
LP_FAST_COEF = 0.6

FADERS_GRID_MAPPING = (16,1)
FADER_GRIDBOX = (1,3)
# DEFAULT_FADER_HANDLE_HEIGHT = 2
# DEFAULT_FADER_BODY_COLOR = (100,100,200)
# DEFAULT_FADER_HANDLE_COLOR = (200,200,200)
# DEFAULT_FADER_TICKS_COLOR = (20,20,20)
# DEFAULT_FADER_COLORS = (DEFAULT_FADER_BODY_COLOR, DEFAULT_FADER_HANDLE_COLOR, DEFAULT_FADER_TICKS_COLOR)

SENSOR_COLOR = (20,60,150)
SENSOR_HOVER_COLOR = colorMult(SENSOR_COLOR, HOVER_COLOR_MULTS)
SENSOR_ACTIVE_COLOR = (SENSOR_HOVER_COLOR)
SENSOR_INACTIVE_COLOR = (70,70,60)
DEFAULT_COLORS = [SENSOR_COLOR, SENSOR_ACTIVE_COLOR, SENSOR_INACTIVE_COLOR]
LED_COLORS = [(20,20,25),(255,140,80)]
LED_SIZE_PX = (GRID_SIZE_PX_X, BRICKS_OUTLINE_WIDTH_PX)
LED_TIMEOUT_FRAMES = 4

STATUS_BOX_GRID_MAPPING = (1,1)

MINIMUM_GRIDBOX = (1,1)
SENSOR_GRID_MAPPING = (8,3)
SENSOR_GRIDBOX = (3,3)
DEFAULT_STATUS_BOX_GRID_H = 4

FRAMERATE = 60

SENSORSAPPING = [
  [0, 3, 6, 9, 12, 15, 18, 21],
  [1, 4, 7, 10, 13, 16, 19, 22],
  [2, 5, 8, 11, 14, 17, 20, 23],
]

privateAutomindTouchSensorCounter = 0
privateFadersCounter = 0